-- Re-file pSEO pages whose city is not in their declared country.
-- 86 cities across 9 countries, ~1,034 rows currently filed as country='in'.
-- Only `country` changes: it derives the locale, URL prefix and hreflang.
-- `slug` is globally unique and untouched, so nothing collides.
--
-- Run STEP 1 first and eyeball it. STEP 2 writes. STEP 3 verifies.

-- ── STEP 1: preview (read-only) ───────────────────────────────────────────────
WITH m(city_slug, correct_country) AS (VALUES
    ('abha','sa'),
    ('al-ahsa','sa'),
    ('al-khor','qa'),
    ('al-rayyan','qa'),
    ('al-wakrah','qa'),
    ('angeles','ph'),
    ('bacolod','ph'),
    ('baguio','ph'),
    ('bandung','id'),
    ('bangkok','th'),
    ('batam','id'),
    ('bekasi','id'),
    ('bogor','id'),
    ('budaiya','bh'),
    ('cagayan-de-oro','ph'),
    ('cebu-city','ph'),
    ('chiang-mai','th'),
    ('chiang-rai','th'),
    ('cyberjaya','my'),
    ('dammam','sa'),
    ('davao-city','ph'),
    ('denpasar','id'),
    ('depok','id'),
    ('dhahran','sa'),
    ('doha','qa'),
    ('fahaheel','kw'),
    ('farwaniya','kw'),
    ('george-town','my'),
    ('hat-yai','th'),
    ('hawalli','kw'),
    ('hua-hin','th'),
    ('iloilo-city','ph'),
    ('ipoh','my'),
    ('isa-town','bh'),
    ('jakarta','id'),
    ('jeddah','sa'),
    ('johor-bahru','my'),
    ('jubail','sa'),
    ('khobar','sa'),
    ('khon-kaen','th'),
    ('koh-samui','th'),
    ('kota-kinabalu','my'),
    ('kuala-lumpur','my'),
    ('kuching','my'),
    ('kuwait-city','kw'),
    ('las-pi-as','ph'),
    ('lusail','qa'),
    ('makassar','id'),
    ('makati','ph'),
    ('malacca','my'),
    ('malang','id'),
    ('manama','bh'),
    ('mandaue','ph'),
    ('mangaf','kw'),
    ('manila','ph'),
    ('mecca','sa'),
    ('medan','id'),
    ('medina','sa'),
    ('muharraq','bh'),
    ('muscat','om'),
    ('nizwa','om'),
    ('nonthaburi','th'),
    ('palembang','id'),
    ('para-aque','ph'),
    ('pasig','ph'),
    ('pattaya','th'),
    ('petaling-jaya','my'),
    ('phuket','th'),
    ('putrajaya','my'),
    ('quezon-city','ph'),
    ('riffa','bh'),
    ('riyadh','sa'),
    ('salalah','om'),
    ('salmiya','kw'),
    ('seeb','om'),
    ('semarang','id'),
    ('shah-alam','my'),
    ('sohar','om'),
    ('subang-jaya','my'),
    ('sur','om'),
    ('surabaya','id'),
    ('tabuk','sa'),
    ('taguig','ph'),
    ('taif','sa'),
    ('tangerang','id'),
    ('yogyakarta','id')
)
SELECT p.country AS now_filed_as, m.correct_country, COUNT(*) AS pages
FROM pseo_pages p JOIN m ON m.city_slug = p.city_slug
WHERE p.country <> m.correct_country
GROUP BY 1, 2 ORDER BY pages DESC;


-- ── STEP 2: apply ─────────────────────────────────────────────────────────────
-- Wrapped in a transaction. Check the row count before COMMIT.
BEGIN;

WITH m(city_slug, correct_country) AS (VALUES
    ('abha','sa'),
    ('al-ahsa','sa'),
    ('al-khor','qa'),
    ('al-rayyan','qa'),
    ('al-wakrah','qa'),
    ('angeles','ph'),
    ('bacolod','ph'),
    ('baguio','ph'),
    ('bandung','id'),
    ('bangkok','th'),
    ('batam','id'),
    ('bekasi','id'),
    ('bogor','id'),
    ('budaiya','bh'),
    ('cagayan-de-oro','ph'),
    ('cebu-city','ph'),
    ('chiang-mai','th'),
    ('chiang-rai','th'),
    ('cyberjaya','my'),
    ('dammam','sa'),
    ('davao-city','ph'),
    ('denpasar','id'),
    ('depok','id'),
    ('dhahran','sa'),
    ('doha','qa'),
    ('fahaheel','kw'),
    ('farwaniya','kw'),
    ('george-town','my'),
    ('hat-yai','th'),
    ('hawalli','kw'),
    ('hua-hin','th'),
    ('iloilo-city','ph'),
    ('ipoh','my'),
    ('isa-town','bh'),
    ('jakarta','id'),
    ('jeddah','sa'),
    ('johor-bahru','my'),
    ('jubail','sa'),
    ('khobar','sa'),
    ('khon-kaen','th'),
    ('koh-samui','th'),
    ('kota-kinabalu','my'),
    ('kuala-lumpur','my'),
    ('kuching','my'),
    ('kuwait-city','kw'),
    ('las-pi-as','ph'),
    ('lusail','qa'),
    ('makassar','id'),
    ('makati','ph'),
    ('malacca','my'),
    ('malang','id'),
    ('manama','bh'),
    ('mandaue','ph'),
    ('mangaf','kw'),
    ('manila','ph'),
    ('mecca','sa'),
    ('medan','id'),
    ('medina','sa'),
    ('muharraq','bh'),
    ('muscat','om'),
    ('nizwa','om'),
    ('nonthaburi','th'),
    ('palembang','id'),
    ('para-aque','ph'),
    ('pasig','ph'),
    ('pattaya','th'),
    ('petaling-jaya','my'),
    ('phuket','th'),
    ('putrajaya','my'),
    ('quezon-city','ph'),
    ('riffa','bh'),
    ('riyadh','sa'),
    ('salalah','om'),
    ('salmiya','kw'),
    ('seeb','om'),
    ('semarang','id'),
    ('shah-alam','my'),
    ('sohar','om'),
    ('subang-jaya','my'),
    ('sur','om'),
    ('surabaya','id'),
    ('tabuk','sa'),
    ('taguig','ph'),
    ('taif','sa'),
    ('tangerang','id'),
    ('yogyakarta','id')
)
UPDATE pseo_pages p
SET country = m.correct_country, updated_at = NOW()
FROM m
WHERE m.city_slug = p.city_slug AND p.country <> m.correct_country;

-- expect ~1034. If it is wildly different, ROLLBACK instead.
COMMIT;


-- ── STEP 3: verify ────────────────────────────────────────────────────────────
SELECT country, COUNT(*) AS pages
FROM pseo_pages GROUP BY 1 ORDER BY pages DESC;

-- Re-running STEP 1 should now return zero rows.
