"""add_comparison_models

Revision ID: 033a1834c4f1
Revises: 3b57127ebb70
Create Date: 2026-06-22 19:31:55.316214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '033a1834c4f1'
down_revision = '3b57127ebb70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_groups_id'), ['id'], unique=False)
        batch_op.create_index('ix_custom_groups_org_name', ['organization_id', 'name'], unique=True)
        batch_op.create_index(batch_op.f('ix_custom_groups_organization_id'), ['organization_id'], unique=False)

    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regions_id'), ['id'], unique=False)
        batch_op.create_index('ix_regions_org_name', ['organization_id', 'name'], unique=True)
        batch_op.create_index(batch_op.f('ix_regions_organization_id'), ['organization_id'], unique=False)

    op.create_table('custom_group_daily_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('custom_group_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('profile_views', sa.Integer(), nullable=False),
    sa.Column('search_impressions', sa.Integer(), nullable=False),
    sa.Column('maps_views', sa.Integer(), nullable=False),
    sa.Column('desktop_search_impressions', sa.Integer(), nullable=False),
    sa.Column('mobile_search_impressions', sa.Integer(), nullable=False),
    sa.Column('desktop_maps_impressions', sa.Integer(), nullable=False),
    sa.Column('mobile_maps_impressions', sa.Integer(), nullable=False),
    sa.Column('phone_calls', sa.Integer(), nullable=False),
    sa.Column('website_clicks', sa.Integer(), nullable=False),
    sa.Column('direction_requests', sa.Integer(), nullable=False),
    sa.Column('searches_direct', sa.Integer(), nullable=False),
    sa.Column('searches_indirect', sa.Integer(), nullable=False),
    sa.Column('searches_chain', sa.Integer(), nullable=False),
    sa.Column('reviews_received', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('positive_review_count', sa.Integer(), nullable=False),
    sa.Column('neutral_review_count', sa.Integer(), nullable=False),
    sa.Column('negative_review_count', sa.Integer(), nullable=False),
    sa.Column('avg_sentiment_score', sa.Float(), nullable=True),
    sa.Column('response_rate', sa.Float(), nullable=False),
    sa.Column('avg_response_time_hours', sa.Float(), nullable=True),
    sa.Column('click_through_rate', sa.Float(), nullable=True),
    sa.Column('call_conversion_rate', sa.Float(), nullable=True),
    sa.Column('direction_conversion_rate', sa.Float(), nullable=True),
    sa.Column('avg_rank', sa.Float(), nullable=True),
    sa.Column('solv', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['custom_group_id'], ['custom_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_group_id', 'date', 'provider', name='uq_custom_group_daily_provider')
    )
    with op.batch_alter_table('custom_group_daily_insights', schema=None) as batch_op:
        batch_op.create_index('idx_cg_insights_cg_date', ['custom_group_id', 'date'], unique=False)
        batch_op.create_index('idx_cg_insights_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_group_daily_insights_custom_group_id'), ['custom_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_group_daily_insights_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_group_daily_insights_organization_id'), ['organization_id'], unique=False)

    op.create_table('custom_group_locations',
    sa.Column('custom_group_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custom_group_id'], ['custom_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('custom_group_id', 'location_id')
    )
    op.create_table('region_daily_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('profile_views', sa.Integer(), nullable=False),
    sa.Column('search_impressions', sa.Integer(), nullable=False),
    sa.Column('maps_views', sa.Integer(), nullable=False),
    sa.Column('desktop_search_impressions', sa.Integer(), nullable=False),
    sa.Column('mobile_search_impressions', sa.Integer(), nullable=False),
    sa.Column('desktop_maps_impressions', sa.Integer(), nullable=False),
    sa.Column('mobile_maps_impressions', sa.Integer(), nullable=False),
    sa.Column('phone_calls', sa.Integer(), nullable=False),
    sa.Column('website_clicks', sa.Integer(), nullable=False),
    sa.Column('direction_requests', sa.Integer(), nullable=False),
    sa.Column('searches_direct', sa.Integer(), nullable=False),
    sa.Column('searches_indirect', sa.Integer(), nullable=False),
    sa.Column('searches_chain', sa.Integer(), nullable=False),
    sa.Column('reviews_received', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('positive_review_count', sa.Integer(), nullable=False),
    sa.Column('neutral_review_count', sa.Integer(), nullable=False),
    sa.Column('negative_review_count', sa.Integer(), nullable=False),
    sa.Column('avg_sentiment_score', sa.Float(), nullable=True),
    sa.Column('response_rate', sa.Float(), nullable=False),
    sa.Column('avg_response_time_hours', sa.Float(), nullable=True),
    sa.Column('click_through_rate', sa.Float(), nullable=True),
    sa.Column('call_conversion_rate', sa.Float(), nullable=True),
    sa.Column('direction_conversion_rate', sa.Float(), nullable=True),
    sa.Column('avg_rank', sa.Float(), nullable=True),
    sa.Column('solv', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'date', 'provider', name='uq_region_daily_provider')
    )
    with op.batch_alter_table('region_daily_insights', schema=None) as batch_op:
        batch_op.create_index('idx_region_insights_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index('idx_region_insights_region_date', ['region_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_region_daily_insights_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_region_daily_insights_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_region_daily_insights_region_id'), ['region_id'], unique=False)

    op.create_table('region_locations',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('region_id', 'location_id')
    )
    op.create_table('saved_comparison_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('group_by', sa.String(), nullable=False),
    sa.Column('filters_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_comparison_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_comparison_views_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_comparison_views_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_comparison_views_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_saved_views_org_user', ['organization_id', 'user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_comparison_views', schema=None) as batch_op:
        batch_op.drop_index('ix_saved_views_org_user')
        batch_op.drop_index(batch_op.f('ix_saved_comparison_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_comparison_views_organization_id'))
        batch_op.drop_index(batch_op.f('ix_saved_comparison_views_id'))

    op.drop_table('saved_comparison_views')
    op.drop_table('region_locations')
    with op.batch_alter_table('region_daily_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_region_daily_insights_region_id'))
        batch_op.drop_index(batch_op.f('ix_region_daily_insights_organization_id'))
        batch_op.drop_index(batch_op.f('ix_region_daily_insights_id'))
        batch_op.drop_index('idx_region_insights_region_date')
        batch_op.drop_index('idx_region_insights_org_date')

    op.drop_table('region_daily_insights')
    op.drop_table('custom_group_locations')
    with op.batch_alter_table('custom_group_daily_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_group_daily_insights_organization_id'))
        batch_op.drop_index(batch_op.f('ix_custom_group_daily_insights_id'))
        batch_op.drop_index(batch_op.f('ix_custom_group_daily_insights_custom_group_id'))
        batch_op.drop_index('idx_cg_insights_org_date')
        batch_op.drop_index('idx_cg_insights_cg_date')

    op.drop_table('custom_group_daily_insights')
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regions_organization_id'))
        batch_op.drop_index('ix_regions_org_name')
        batch_op.drop_index(batch_op.f('ix_regions_id'))

    op.drop_table('regions')
    with op.batch_alter_table('custom_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_groups_organization_id'))
        batch_op.drop_index('ix_custom_groups_org_name')
        batch_op.drop_index(batch_op.f('ix_custom_groups_id'))

    op.drop_table('custom_groups')
    # ### end Alembic commands ###
