"""Add GBP Dynamic Attribute Engine models

Revision ID: 04c36e3e3906
Revises: 50533dc0dd33
Create Date: 2026-06-06 22:44:09.845204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04c36e3e3906'
down_revision = '50533dc0dd33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gbp_attribute_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.String(length=100), nullable=False),
    sa.Column('region_code', sa.String(length=2), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('group_display_name', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('is_repeatable', sa.Boolean(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('options_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gbp_attribute_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gbp_attribute_definitions_id'), ['id'], unique=False)

    op.create_table('gbp_attribute_metadata',
    sa.Column('category_id', sa.String(length=100), nullable=False),
    sa.Column('region_code', sa.String(length=2), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('metadata_version', sa.String(length=50), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('category_id', 'region_code', 'language_code')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('draft_attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('last_google_sync', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('last_google_sync')
        batch_op.drop_column('draft_attributes')
        batch_op.drop_column('google_attributes')

    op.drop_table('gbp_attribute_metadata')
    with op.batch_alter_table('gbp_attribute_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gbp_attribute_definitions_id'))

    op.drop_table('gbp_attribute_definitions')
    # ### end Alembic commands ###
