"""add_rating_and_reviews

Revision ID: 0c81763e2072
Revises: 2b3c4d5e6f7a
Create Date: 2026-05-20 18:58:59.168914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c81763e2072'
down_revision = '2b3c4d5e6f7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('average_rating', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('total_reviews', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'total_reviews')
    op.drop_column('locations', 'average_rating')
    # ### end Alembic commands ###
