"""add insights sync columns to organization sync state

Revision ID: 0d7ba9c90f8d
Revises: a4842bd48f8a
Create Date: 2026-06-05 16:27:39.194574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7ba9c90f8d'
down_revision = 'a4842bd48f8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_daily_insights', schema=None) as batch_op:
        batch_op.create_index('idx_insights_org_date_loc', ['organization_id', 'date', 'location_id'], unique=False)

    with op.batch_alter_table('organization_sync_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insights_sync_in_progress', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('last_insights_sync_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_insights_sync_error', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_insights_sync_started_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_insights_sync_completed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('last_sync_error',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_sync_states', schema=None) as batch_op:
        batch_op.alter_column('last_sync_error',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('last_insights_sync_completed_at')
        batch_op.drop_column('last_insights_sync_started_at')
        batch_op.drop_column('last_insights_sync_error')
        batch_op.drop_column('last_insights_sync_status')
        batch_op.drop_column('insights_sync_in_progress')

    with op.batch_alter_table('location_daily_insights', schema=None) as batch_op:
        batch_op.drop_index('idx_insights_org_date_loc')

    # ### end Alembic commands ###
