"""add_location_edits_activity_log_v2

Revision ID: 0f18c6e9db3a
Revises: a492f258cf7c
Create Date: 2026-05-31 12:18:31.519917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f18c6e9db3a'
down_revision = 'a492f258cf7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log_archive', schema=None) as batch_op:
        batch_op.create_index('idx_activity_archive_location', ['location_id', 'created_at'], unique=False)
        batch_op.create_index('idx_activity_archive_org', ['organization_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_archive_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_archive_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_archive_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_archive_organization_id'), ['organization_id'], unique=False)

    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index('idx_activity_log_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_activity_log_location_created', ['location_id', 'created_at'], unique=False)
        batch_op.create_index('idx_activity_log_org_created', ['organization_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_organization_id'), ['organization_id'], unique=False)

    op.create_table('location_edits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'REJECTED', name='locationeditstatus'), nullable=False),
    sa.Column('rejection_note', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('publish_attempts', sa.Integer(), nullable=False),
    sa.Column('google_error_code', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('warning_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('requested_publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_edits', schema=None) as batch_op:
        batch_op.create_index('idx_location_edits_location_status', ['location_id', 'status'], unique=False)
        batch_op.create_index('idx_location_edits_org_created', ['organization_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_edits_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_edits_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_edits_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_edits_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_edits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_edits_status'))
        batch_op.drop_index(batch_op.f('ix_location_edits_organization_id'))
        batch_op.drop_index(batch_op.f('ix_location_edits_location_id'))
        batch_op.drop_index(batch_op.f('ix_location_edits_id'))
        batch_op.drop_index('idx_location_edits_org_created')
        batch_op.drop_index('idx_location_edits_location_status')

    op.drop_table('location_edits')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_organization_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_location_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_activity_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_log_correlation_id'))
        batch_op.drop_index('idx_activity_log_org_created')
        batch_op.drop_index('idx_activity_log_location_created')
        batch_op.drop_index('idx_activity_log_entity')

    op.drop_table('activity_log')
    with op.batch_alter_table('activity_log_archive', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_archive_organization_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_archive_location_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_archive_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_archive_correlation_id'))
        batch_op.drop_index('idx_activity_archive_org')
        batch_op.drop_index('idx_activity_archive_location')

    op.drop_table('activity_log_archive')
    # ### end Alembic commands ###
