"""add_billing_and_webhook_idempotency_models

Revision ID: 0fa7571be756
Revises: 9f12a3b4c5d6
Create Date: 2026-06-10 16:59:17.814024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa7571be756'
down_revision = '9f12a3b4c5d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razorpay_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_webhook_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_webhook_events_razorpay_event_id'), ['razorpay_event_id'], unique=True)

    op.create_table('billing_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_transactions_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(), server_default=sa.text("'trial'"), nullable=True))
        batch_op.add_column(sa.Column('billing_cycle', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(), server_default=sa.text("'trial_pending_activation'"), nullable=True))
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('grace_period_ends_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('location_quota', sa.Integer(), server_default=sa.text('5'), nullable=True))
        batch_op.add_column(sa.Column('monthly_ai_credits_balance', sa.Integer(), server_default=sa.text('200'), nullable=True))
        batch_op.add_column(sa.Column('topup_ai_credits_balance', sa.Integer(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('ai_credits_reset_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('razorpay_customer_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('razorpay_subscription_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index('idx_org_subscription_status_ends_at', ['subscription_status', 'subscription_ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_razorpay_customer_id'), ['razorpay_customer_id'], unique=False)

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'ai_credits_balance' in [c['name'] for c in inspector.get_columns('organizations')]:
        with op.batch_alter_table('organizations') as batch_op:
            batch_op.drop_column('ai_credits_balance')

    bind.execute(
        sa.text(
            """
            UPDATE organizations
            SET plan = 'trial',
                subscription_status = 'trial_pending_activation',
                location_quota = 5,
                monthly_ai_credits_balance = 200,
                topup_ai_credits_balance = 0
            WHERE plan IS NULL
            """
        )
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_razorpay_customer_id'))
        batch_op.drop_index('idx_org_subscription_status_ends_at')
        batch_op.drop_column('subscription_ends_at')
        batch_op.drop_column('razorpay_subscription_id')
        batch_op.drop_column('razorpay_customer_id')
        batch_op.drop_column('ai_credits_reset_date')
        batch_op.drop_column('topup_ai_credits_balance')
        batch_op.drop_column('monthly_ai_credits_balance')
        batch_op.drop_column('location_quota')
        batch_op.drop_column('grace_period_ends_at')
        batch_op.drop_column('trial_ends_at')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('billing_cycle')
        batch_op.drop_column('plan')

    with op.batch_alter_table('billing_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_transactions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_billing_transactions_id'))

    op.drop_table('billing_transactions')
    with op.batch_alter_table('billing_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_webhook_events_razorpay_event_id'))
        batch_op.drop_index(batch_op.f('ix_billing_webhook_events_id'))

    op.drop_table('billing_webhook_events')
    # ### end Alembic commands ###
