"""upgrade_post_media_storage

Revision ID: 23cb437ced7d
Revises: 4ba432de4180
Create Date: 2026-05-28 23:32:21.171274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23cb437ced7d'
down_revision = '4ba432de4180'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_key', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('optimized_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('upload_status', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('validation_status', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('log_metadata', sa.JSON(), nullable=True))
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_media', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('log_metadata')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('validation_status')
        batch_op.drop_column('upload_status')
        batch_op.drop_column('optimized_url')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('storage_key')

    # ### end Alembic commands ###
