"""add leaderboard_snapshots table

Revision ID: 30ad7c4a3724
Revises: f1a2b3c4d5e6
Create Date: 2026-06-21 18:18:42.322531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ad7c4a3724'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_version', sa.String(length=20), nullable=False),
    sa.Column('average_rating_raw', sa.Float(), nullable=True),
    sa.Column('response_rate_raw', sa.Float(), nullable=True),
    sa.Column('health_score_raw', sa.Float(), nullable=True),
    sa.Column('review_volume_raw', sa.Integer(), nullable=True),
    sa.Column('engagement_growth_raw', sa.Float(), nullable=True),
    sa.Column('rating_score', sa.Float(), nullable=True),
    sa.Column('response_rate_score', sa.Float(), nullable=True),
    sa.Column('health_score_input', sa.Float(), nullable=True),
    sa.Column('review_volume_score', sa.Float(), nullable=True),
    sa.Column('engagement_growth_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('previous_rank', sa.Integer(), nullable=True),
    sa.Column('rank_movement', sa.Integer(), nullable=True),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('ineligibility_reason', sa.String(), nullable=True),
    sa.Column('streak_count', sa.Integer(), nullable=False),
    sa.Column('most_improved_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'location_id', 'period_label', name='uq_leaderboard_snapshot_period')
    )
    with op.batch_alter_table('leaderboard_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_leaderboard_org_period_rank', ['organization_id', 'period_label', 'rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaderboard_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaderboard_snapshots_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaderboard_snapshots_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaderboard_snapshots_period_label'), ['period_label'], unique=False)



    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('leaderboard_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaderboard_snapshots_period_label'))
        batch_op.drop_index(batch_op.f('ix_leaderboard_snapshots_organization_id'))
        batch_op.drop_index(batch_op.f('ix_leaderboard_snapshots_location_id'))
        batch_op.drop_index(batch_op.f('ix_leaderboard_snapshots_id'))
        batch_op.drop_index('idx_leaderboard_org_period_rank')

    op.drop_table('leaderboard_snapshots')
    # ### end Alembic commands ###
