"""add_geography_fields_to_locations

Revision ID: 3b57127ebb70
Revises: a1c9f4e2b7d0
Create Date: 2026-06-22 19:29:13.408313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b57127ebb70'
down_revision = 'a1c9f4e2b7d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_locations_city'), ['city'], unique=False)
        batch_op.create_index('ix_locations_org_city', ['organization_id', 'city'], unique=False)
        batch_op.create_index('ix_locations_org_state', ['organization_id', 'state'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_state'), ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_state'))
        batch_op.drop_index('ix_locations_org_state')
        batch_op.drop_index('ix_locations_org_city')
        batch_op.drop_index(batch_op.f('ix_locations_city'))
        batch_op.drop_column('postal_code')
        batch_op.drop_column('country')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
    # ### end Alembic commands ###
