"""add_sla_columns_and_indexes

Revision ID: 45de512aa99d
Revises: head_merge_001
Create Date: 2026-05-27 18:22:43.640182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45de512aa99d'
down_revision = 'head_merge_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla_tracking_started_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index('ix_locations_sla_tracking_started_at', ['sla_tracking_started_at'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index('ix_reviews_reply_created_at', ['reply_created_at'], unique=False)
        batch_op.create_index('ix_reviews_sla_lookup', ['organization_id', 'location_id', 'is_deleted', 'is_replied', 'review_created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_sla_lookup')
        batch_op.drop_index('ix_reviews_reply_created_at')
        batch_op.drop_column('reply_created_at')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index('ix_locations_sla_tracking_started_at')
        batch_op.drop_column('sla_tracking_started_at')

    # ### end Alembic commands ###
