"""add_keyword_metrics_and_brand_terms

Revision ID: 4a29ca2897dd
Revises: 7f3a9c1d2e4b
Create Date: 2026-06-12 18:37:54.072561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a29ca2897dd'
down_revision = '7f3a9c1d2e4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_brand_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_brand_terms', schema=None) as batch_op:
        batch_op.create_index('idx_org_brand_terms_org_term', ['organization_id', 'term'], unique=True)
        batch_op.create_index(batch_op.f('ix_organization_brand_terms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_brand_terms_organization_id'), ['organization_id'], unique=False)

    op.create_table('keyword_monthly_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('google_location_id', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('impressions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keyword_monthly_metrics', schema=None) as batch_op:
        batch_op.create_index('idx_keyword_monthly_google_location_id', ['google_location_id'], unique=False)
        batch_op.create_index('idx_keyword_monthly_location_period_kw', ['location_id', 'period_start', 'keyword'], unique=True)
        batch_op.create_index(batch_op.f('ix_keyword_monthly_metrics_google_location_id'), ['google_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_keyword_monthly_metrics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_keyword_monthly_metrics_location_id'), ['location_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_monthly_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_monthly_metrics_location_id'))
        batch_op.drop_index(batch_op.f('ix_keyword_monthly_metrics_id'))
        batch_op.drop_index(batch_op.f('ix_keyword_monthly_metrics_google_location_id'))
        batch_op.drop_index('idx_keyword_monthly_location_period_kw')
        batch_op.drop_index('idx_keyword_monthly_google_location_id')

    op.drop_table('keyword_monthly_metrics')
    with op.batch_alter_table('organization_brand_terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_brand_terms_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organization_brand_terms_id'))
        batch_op.drop_index('idx_org_brand_terms_org_term')

    op.drop_table('organization_brand_terms')
    # ### end Alembic commands ###
