"""add content_hash and location_sync_metadata

Revision ID: 50533dc0dd33
Revises: 0d7ba9c90f8d
Create Date: 2026-06-05 18:10:43.149286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50533dc0dd33'
down_revision = '0d7ba9c90f8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_sync_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_sync_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_reviews_content_hash'), ['content_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_content_hash'))
        batch_op.drop_column('content_hash')

    with op.batch_alter_table('organization_sync_states', schema=None) as batch_op:
        batch_op.drop_column('location_sync_metadata')

    # ### end Alembic commands ###
