"""add microsites table and organization slug

Revision ID: 56311790c76c
Revises: c4e1f0a9d7b2
Create Date: 2026-06-24 15:41:56.130884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56311790c76c'
down_revision = 'c4e1f0a9d7b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microsites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('org_slug', sa.String(), nullable=False),
    sa.Column('location_slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unpublished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', name='uq_microsite_location'),
    sa.UniqueConstraint('org_slug', 'location_slug', name='uq_microsite_org_slug')
    )
    with op.batch_alter_table('microsites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_microsites_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_microsites_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_microsites_status', ['status'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_column('slug')

    with op.batch_alter_table('microsites', schema=None) as batch_op:
        batch_op.drop_index('ix_microsites_status')
        batch_op.drop_index(batch_op.f('ix_microsites_organization_id'))
        batch_op.drop_index(batch_op.f('ix_microsites_id'))

    op.drop_table('microsites')
    # ### end Alembic commands ###
