"""add_rating_and_reviews

Revision ID: 59979441415a
Revises: 0c81763e2072
Create Date: 2026-05-20 19:00:58.806450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59979441415a'
down_revision = '0c81763e2072'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
