"""add_last_opened_at_to_invites

Revision ID: 5c94e212b009
Revises: dd2686289234
Create Date: 2026-05-24 12:44:33.596855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c94e212b009'
down_revision = 'dd2686289234'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_column('last_opened_at')

    # ### end Alembic commands ###
