"""add_sentiment_columns_to_reviews

Revision ID: 60e1d4af4858
Revises: 2c8a1b9e8f6d
Create Date: 2026-05-25 19:37:13.619984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e1d4af4858'
down_revision = '2c8a1b9e8f6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('issue_category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sentiment_tagged_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_reviews_issue_category'), ['issue_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_sentiment'), ['sentiment'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_sentiment'))
        batch_op.drop_index(batch_op.f('ix_reviews_issue_category'))
        batch_op.drop_column('sentiment_tagged_at')
        batch_op.drop_column('issue_category')
        batch_op.drop_column('sentiment')

    # ### end Alembic commands ###
