"""Add idempotency fields and rejection constraints

Revision ID: 7e76ca48c3ac
Revises: fb27a75e8270
Create Date: 2026-06-07 10:30:22.399985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e76ca48c3ac'
down_revision = 'fb27a75e8270'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Consolidate duplicate rejection records
    op.execute("""
    WITH duplicates AS (
        SELECT location_id, attribute_id,
               MIN(first_seen) as min_first,
               MAX(last_seen) as max_last,
               SUM(rejection_count) as total_count,
               MIN(id) as keep_id
        FROM gbp_location_attribute_rejections
        GROUP BY location_id, attribute_id
        HAVING COUNT(*) > 1
    ),
    updated AS (
        UPDATE gbp_location_attribute_rejections r
        SET first_seen = d.min_first,
            last_seen = d.max_last,
            rejection_count = d.total_count
        FROM duplicates d
        WHERE r.id = d.keep_id
    )
    DELETE FROM gbp_location_attribute_rejections
    WHERE id NOT IN (
        SELECT MIN(id)
        FROM gbp_location_attribute_rejections
        GROUP BY location_id, attribute_id
    );
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gbp_location_attribute_rejections', schema=None) as batch_op:
        batch_op.alter_column('first_seen',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('last_seen',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.create_unique_constraint('uq_gbp_location_attribute_rejections_loc_attr', ['location_id', 'attribute_id'])
        batch_op.create_index('ix_gbp_loc_attr_rejections_loc_supp_last_seen', ['location_id', 'suppressed', 'last_seen'], unique=False)

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_publish_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_published_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('last_published_at')
        batch_op.drop_column('last_publish_hash')

    with op.batch_alter_table('gbp_location_attribute_rejections', schema=None) as batch_op:
        batch_op.drop_index('ix_gbp_loc_attr_rejections_loc_supp_last_seen')
        batch_op.drop_constraint('uq_gbp_location_attribute_rejections_loc_attr', type_='unique')
        batch_op.alter_column('last_seen',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('first_seen',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###
