"""add organization_id index to locations

Revision ID: 8c3b1a2d4e5f
Revises: 6a25b1c50d0b
Create Date: 2026-06-07 08:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8c3b1a2d4e5f'
down_revision = '6a25b1c50d0b'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_locations_organization_id'), 'locations', ['organization_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_organization_id'), table_name='locations')
    # ### end Alembic commands ###
