"""fix_billing_schema_mismatches

Revision ID: 9a8b150e74ac
Revises: 0fa7571be756
Create Date: 2026-06-10 17:41:24.314117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8b150e74ac'
down_revision = '0fa7571be756'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('razorpay_payment_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('razorpay_order_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('razorpay_subscription_id', sa.String(), nullable=True))
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('billing_webhook_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload', sa.JSON(), nullable=True))

    with op.batch_alter_table('gbp_location_attribute_rejections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gbp_loc_attr_rejections_loc_supp_last_seen'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gbp_location_attribute_rejections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gbp_loc_attr_rejections_loc_supp_last_seen'), ['location_id', 'suppressed', 'last_seen'], unique=False)

    with op.batch_alter_table('billing_webhook_events', schema=None) as batch_op:
        batch_op.drop_column('payload')

    with op.batch_alter_table('billing_transactions', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('razorpay_subscription_id')
        batch_op.drop_column('razorpay_order_id')
        batch_op.drop_column('razorpay_payment_id')
        batch_op.drop_column('status')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
