"""add review velocity to leaderboard snapshots

Revision ID: 9bca78c19bf6
Revises: 30ad7c4a3724
Create Date: 2026-06-22 06:50:37.920885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bca78c19bf6'
down_revision = '30ad7c4a3724'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboard_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_velocity_raw', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_velocity_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboard_snapshots', schema=None) as batch_op:
        batch_op.drop_column('review_velocity_score')
        batch_op.drop_column('review_velocity_raw')
    # ### end Alembic commands ###
