"""add_location_state_tracking

Revision ID: 9f12a3b4c5d6
Revises: 3c9354df6c8b
Create Date: 2026-06-08 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f12a3b4c5d6'
down_revision = 'c79d10e88cfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('locations', sa.Column('is_suspended', sa.Boolean(), nullable=True))
    op.add_column('locations', sa.Column('is_duplicate', sa.Boolean(), nullable=True))
    op.create_index('ix_locations_is_suspended', 'locations', ['is_suspended'])
    op.create_index('ix_locations_is_duplicate', 'locations', ['is_duplicate'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_locations_is_duplicate', table_name='locations')
    op.drop_index('ix_locations_is_suspended', table_name='locations')
    op.drop_column('locations', 'is_duplicate')
    op.drop_column('locations', 'is_suspended')
    op.drop_column('locations', 'is_verified')
    # ### end Alembic commands ###