"""add_primary_post_and_scheduled_at

Revision ID: a492f258cf7c
Revises: d2038509f4e3
Create Date: 2026-05-29 17:52:22.161105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a492f258cf7c'
down_revision = 'd2038509f4e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'posts', ['primary_post_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('scheduled_at')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('primary_post_id')

    # ### end Alembic commands ###
