"""add_gbp_location_attribute_rejection

Revision ID: a6e5cc033b9e
Revises: 04c36e3e3906
Create Date: 2026-06-06 19:20:35.190787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e5cc033b9e'
down_revision = '04c36e3e3906'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gbp_location_attribute_rejections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.String(length=255), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('rejection_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gbp_location_attribute_rejections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gbp_location_attribute_rejections_attribute_id'), ['attribute_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gbp_location_attribute_rejections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gbp_location_attribute_rejections_location_id'), ['location_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gbp_location_attribute_rejections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gbp_location_attribute_rejections_location_id'))
        batch_op.drop_index(batch_op.f('ix_gbp_location_attribute_rejections_id'))
        batch_op.drop_index(batch_op.f('ix_gbp_location_attribute_rejections_attribute_id'))

    op.drop_table('gbp_location_attribute_rejections')
    # ### end Alembic commands ###
