"""add_reply_templates_table

Revision ID: c055e8206e83
Revises: ed05ec24150a
Create Date: 2026-06-15 16:57:18.718139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c055e8206e83'
down_revision = 'ed05ec24150a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('star_rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('star_rating >= 1 AND star_rating <= 5', name='ck_reply_templates_star_rating'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'star_rating', 'title', name='uq_reply_templates_org_star_title')
    )
    with op.batch_alter_table('reply_templates', schema=None) as batch_op:
        batch_op.create_index('idx_reply_templates_org_star', ['organization_id', 'star_rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_reply_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reply_templates_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reply_templates_organization_id'))
        batch_op.drop_index(batch_op.f('ix_reply_templates_id'))
        batch_op.drop_index('idx_reply_templates_org_star')

    op.drop_table('reply_templates')
    # ### end Alembic commands ###
