"""add_reviews_table

Revision ID: cb49eb4293aa
Revises: bd3797d45171
Create Date: 2026-05-21 18:35:23.766472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb49eb4293aa'
down_revision = 'bd3797d45171'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_review_id', sa.String(), nullable=False),
    sa.Column('reviewer_name', sa.String(), nullable=False),
    sa.Column('reviewer_profile_photo', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_replied', sa.Boolean(), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('review_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_review_id', name='uq_review_provider_id')
    )
    op.create_index('idx_reviews_location_created_at_desc', 'reviews', ['location_id', sa.text('review_created_at DESC')], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_location_id'), 'reviews', ['location_id'], unique=False)
    op.create_index(op.f('ix_reviews_organization_id'), 'reviews', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reviews_provider_review_id'), 'reviews', ['provider_review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_provider_review_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_organization_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_location_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index('idx_reviews_location_created_at_desc', table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
