"""add_composite_indexes_to_publish_jobs

Revision ID: d2038509f4e3
Revises: 3c9354df6c8b
Create Date: 2026-05-29 17:23:45.806120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2038509f4e3'
down_revision = '3c9354df6c8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publish_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_publish_jobs_campaign_status', ['campaign_id', 'status'], unique=False)
        batch_op.create_index('idx_publish_jobs_org_status', ['organization_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publish_jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_publish_jobs_org_status')
        batch_op.drop_index('idx_publish_jobs_campaign_status')

    # ### end Alembic commands ###
