"""make_review_unique_constraint_composite

Revision ID: dabb5ab65d4a
Revises: f7b2c1d9e8a3
Create Date: 2026-05-24 19:09:08.590562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dabb5ab65d4a'
down_revision = 'f7b2c1d9e8a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('uq_review_provider_id', type_='unique')
        batch_op.create_unique_constraint('uq_review_provider_id', ['location_id', 'provider', 'provider_review_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('uq_review_provider_id', type_='unique')
        batch_op.create_unique_constraint('uq_review_provider_id', ['provider', 'provider_review_id'])

    # ### end Alembic commands ###
