"""add_location_daily_insights

Revision ID: f35c21fa1306
Revises: add_description_001
Create Date: 2026-06-02 18:16:02.877345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35c21fa1306'
down_revision = 'add_description_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_daily_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('profile_views', sa.Integer(), nullable=False),
    sa.Column('search_impressions', sa.Integer(), nullable=False),
    sa.Column('maps_views', sa.Integer(), nullable=False),
    sa.Column('phone_calls', sa.Integer(), nullable=False),
    sa.Column('website_clicks', sa.Integer(), nullable=False),
    sa.Column('direction_requests', sa.Integer(), nullable=False),
    sa.Column('searches_direct', sa.Integer(), nullable=False),
    sa.Column('searches_indirect', sa.Integer(), nullable=False),
    sa.Column('searches_chain', sa.Integer(), nullable=False),
    sa.Column('reviews_received', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('positive_review_count', sa.Integer(), nullable=False),
    sa.Column('neutral_review_count', sa.Integer(), nullable=False),
    sa.Column('negative_review_count', sa.Integer(), nullable=False),
    sa.Column('avg_sentiment_score', sa.Float(), nullable=True),
    sa.Column('response_rate', sa.Float(), nullable=False),
    sa.Column('avg_response_time_hours', sa.Float(), nullable=True),
    sa.Column('click_through_rate', sa.Float(), nullable=True),
    sa.Column('call_conversion_rate', sa.Float(), nullable=True),
    sa.Column('direction_conversion_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'date', 'provider', name='uq_location_daily_provider')
    )
    with op.batch_alter_table('location_daily_insights', schema=None) as batch_op:
        batch_op.create_index('idx_insights_location_date', ['location_id', 'date'], unique=False)
        batch_op.create_index('idx_insights_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index('idx_insights_provider', ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_daily_insights_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_daily_insights_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_daily_insights_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_insights_sync_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('attention_needed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('attention_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('attention_updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('attention_updated_at')
        batch_op.drop_column('attention_reason')
        batch_op.drop_column('attention_needed')
        batch_op.drop_column('last_insights_sync_at')

    with op.batch_alter_table('location_daily_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_daily_insights_organization_id'))
        batch_op.drop_index(batch_op.f('ix_location_daily_insights_location_id'))
        batch_op.drop_index(batch_op.f('ix_location_daily_insights_id'))
        batch_op.drop_index('idx_insights_provider')
        batch_op.drop_index('idx_insights_org_date')
        batch_op.drop_index('idx_insights_location_date')

    op.drop_table('location_daily_insights')
    # ### end Alembic commands ###
