"""Add GroupDailyInsight and SavedComparisonView.is_shared

Revision ID: f718060d3dbe
Revises: 033a1834c4f1
Create Date: 2026-06-22 19:43:41.256102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f718060d3dbe'
down_revision = '033a1834c4f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_daily_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('group_type', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('profile_views', sa.Integer(), nullable=False),
    sa.Column('search_impressions', sa.Integer(), nullable=False),
    sa.Column('maps_views', sa.Integer(), nullable=False),
    sa.Column('desktop_search_impressions', sa.Integer(), nullable=False),
    sa.Column('mobile_search_impressions', sa.Integer(), nullable=False),
    sa.Column('desktop_maps_impressions', sa.Integer(), nullable=False),
    sa.Column('mobile_maps_impressions', sa.Integer(), nullable=False),
    sa.Column('phone_calls', sa.Integer(), nullable=False),
    sa.Column('website_clicks', sa.Integer(), nullable=False),
    sa.Column('direction_requests', sa.Integer(), nullable=False),
    sa.Column('searches_direct', sa.Integer(), nullable=False),
    sa.Column('searches_indirect', sa.Integer(), nullable=False),
    sa.Column('searches_chain', sa.Integer(), nullable=False),
    sa.Column('reviews_received', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('positive_review_count', sa.Integer(), nullable=False),
    sa.Column('neutral_review_count', sa.Integer(), nullable=False),
    sa.Column('negative_review_count', sa.Integer(), nullable=False),
    sa.Column('avg_sentiment_score', sa.Float(), nullable=True),
    sa.Column('response_rate', sa.Float(), nullable=False),
    sa.Column('avg_response_time_hours', sa.Float(), nullable=True),
    sa.Column('click_through_rate', sa.Float(), nullable=True),
    sa.Column('call_conversion_rate', sa.Float(), nullable=True),
    sa.Column('direction_conversion_rate', sa.Float(), nullable=True),
    sa.Column('avg_rank', sa.Float(), nullable=True),
    sa.Column('solv', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_type', 'group_id', 'date', 'provider', name='uq_group_daily_provider')
    )
    with op.batch_alter_table('group_daily_insights', schema=None) as batch_op:
        batch_op.create_index('idx_group_insights_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index('idx_group_insights_type_id_date', ['group_type', 'group_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_daily_insights_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_daily_insights_group_type'), ['group_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_daily_insights_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_daily_insights_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('custom_group_daily_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cg_insights_cg_date'))
        batch_op.drop_index(batch_op.f('idx_cg_insights_org_date'))
        batch_op.drop_index(batch_op.f('ix_custom_group_daily_insights_custom_group_id'))
        batch_op.drop_index(batch_op.f('ix_custom_group_daily_insights_id'))
        batch_op.drop_index(batch_op.f('ix_custom_group_daily_insights_organization_id'))

    op.drop_table('custom_group_daily_insights')
    with op.batch_alter_table('region_daily_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_region_insights_org_date'))
        batch_op.drop_index(batch_op.f('idx_region_insights_region_date'))
        batch_op.drop_index(batch_op.f('ix_region_daily_insights_id'))
        batch_op.drop_index(batch_op.f('ix_region_daily_insights_organization_id'))
        batch_op.drop_index(batch_op.f('ix_region_daily_insights_region_id'))

    op.drop_table('region_daily_insights')
    with op.batch_alter_table('saved_comparison_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_shared', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_comparison_views', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_shared')

    op.create_table('region_daily_insights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profile_views', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('search_impressions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('maps_views', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('desktop_search_impressions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mobile_search_impressions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('desktop_maps_impressions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mobile_maps_impressions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone_calls', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('website_clicks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('direction_requests', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('searches_direct', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('searches_indirect', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('searches_chain', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviews_received', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('positive_review_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('neutral_review_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('negative_review_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('response_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_response_time_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('click_through_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('call_conversion_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('direction_conversion_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_rank', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('solv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('region_daily_insights_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('region_daily_insights_region_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('region_daily_insights_pkey')),
    sa.UniqueConstraint('region_id', 'date', 'provider', name=op.f('uq_region_daily_provider'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('region_daily_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_region_daily_insights_region_id'), ['region_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_region_daily_insights_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_region_daily_insights_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('idx_region_insights_region_date'), ['region_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('idx_region_insights_org_date'), ['organization_id', 'date'], unique=False)

    op.create_table('custom_group_daily_insights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('custom_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profile_views', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('search_impressions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('maps_views', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('desktop_search_impressions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mobile_search_impressions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('desktop_maps_impressions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mobile_maps_impressions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone_calls', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('website_clicks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('direction_requests', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('searches_direct', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('searches_indirect', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('searches_chain', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviews_received', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('positive_review_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('neutral_review_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('negative_review_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('response_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_response_time_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('click_through_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('call_conversion_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('direction_conversion_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_rank', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('solv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['custom_group_id'], ['custom_groups.id'], name=op.f('custom_group_daily_insights_custom_group_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('custom_group_daily_insights_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('custom_group_daily_insights_pkey')),
    sa.UniqueConstraint('custom_group_id', 'date', 'provider', name=op.f('uq_custom_group_daily_provider'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('custom_group_daily_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_group_daily_insights_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_group_daily_insights_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_group_daily_insights_custom_group_id'), ['custom_group_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_cg_insights_org_date'), ['organization_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('idx_cg_insights_cg_date'), ['custom_group_id', 'date'], unique=False)

    with op.batch_alter_table('group_daily_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_daily_insights_organization_id'))
        batch_op.drop_index(batch_op.f('ix_group_daily_insights_id'))
        batch_op.drop_index(batch_op.f('ix_group_daily_insights_group_type'))
        batch_op.drop_index(batch_op.f('ix_group_daily_insights_group_id'))
        batch_op.drop_index('idx_group_insights_type_id_date')
        batch_op.drop_index('idx_group_insights_org_date')

    op.drop_table('group_daily_insights')
    # ### end Alembic commands ###
