"""Add category resource name and rejection suppression

Revision ID: fb27a75e8270
Revises: a6e5cc033b9e
Create Date: 2026-06-07 09:57:02.148976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb27a75e8270'
down_revision = 'a6e5cc033b9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gbp_location_attribute_rejections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suppressed', sa.Boolean(), server_default='false', nullable=False))

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_category_resource_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('google_attributes_stale', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('google_attributes_stale')
        batch_op.drop_column('google_category_resource_name')

    with op.batch_alter_table('gbp_location_attribute_rejections', schema=None) as batch_op:
        batch_op.drop_column('suppressed')

    # ### end Alembic commands ###
