"""add_location_health_score

Revision ID: fc18f1744ac5
Revises: f6a7b8c9d0e1
Create Date: 2026-06-12 17:43:05.482344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc18f1744ac5'
down_revision = 'f6a7b8c9d0e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_health_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('potential_score', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('score_version', sa.String(length=20), server_default='HEALTH_V1', nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_recalculated_reason', sa.String(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_health_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_health_scores_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_health_scores_location_id'), ['location_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_health_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_health_scores_location_id'))
        batch_op.drop_index(batch_op.f('ix_location_health_scores_id'))

    op.drop_table('location_health_scores')
    # ### end Alembic commands ###
